--led enumeration
LED_FIRE = 0

LED_FIRE_A_RED = 1
LED_FIRE_A_GREEN = 2

LED_FIRE_B_RED = 3
LED_FIRE_B_GREEN = 4
	
LED_FIRE_D_RED = 5
LED_FIRE_D_GREEN = 6

LED_FIRE_E_RED = 7
LED_FIRE_E_GREEN = 8

LED_LEFT_TOGGLE_RED = 9
LED_LEFT_TOGGLE_GREEN = 10

LED_CENTER_TOGGLE_RED = 11
LED_CENTER_TOGGLE_GREEN = 12

LED_RIGHT_TOGGLE_RED = 13
LED_RIGHT_TOGGLE_GREEN = 14

LED_CASTLE_RED = 15
LED_CASTLE_GREEN = 16

LED_CLUTCH_RED = 17
LED_CLUTCH_GREEN = 18

LED_THROTTLE = 19
LED_COMPLEX_START		  = 100

-- complicated ( two color leds)

LED_COMPLEX_FIRE_A		  = LED_COMPLEX_START + LED_FIRE_A_RED
LED_COMPLEX_FIRE_B		  = LED_COMPLEX_START + LED_FIRE_B_RED
LED_COMPLEX_FIRE_D		  = LED_COMPLEX_START + LED_FIRE_D_RED
LED_COMPLEX_FIRE_E		  = LED_COMPLEX_START + LED_FIRE_E_RED
LED_COMPLEX_LEFT_TOGGLE   = LED_COMPLEX_START + LED_LEFT_TOGGLE_RED
LED_COMPLEX_CENTER_TOGGLE = LED_COMPLEX_START + LED_CENTER_TOGGLE_RED
LED_COMPLEX_RIGHT_TOGGLE  = LED_COMPLEX_START + LED_RIGHT_TOGGLE_RED
LED_COMPLEX_CASTLE		  = LED_COMPLEX_START + LED_CASTLE_RED
LED_COMPLEX_CLUTCH		  = LED_COMPLEX_START + LED_CLUTCH_RED

--led value 

LED_OFF = 0
LED_ON  = 1
	
LED_COMPLEX_VALUE = 100

LED_RED	   = LED_COMPLEX_VALUE + 1
LED_GREEN  = LED_COMPLEX_VALUE + 2
LED_YELLOW = LED_COMPLEX_VALUE + 3
