
local CMS_xsize = 50
local CMS_ysize = 65
fontdescription_ALQ_213 = {
	texture    = "Fonts/font_ALQ_213.tga",
	size      = {8, 8},
	resolution = {512, 512},	
	default    = {CMS_xsize, CMS_ysize}	,
	chars	   = {
		 [1]   = {4,  CMS_xsize, CMS_ysize}, -- ¦ == \4
		 [2]   = {32, CMS_xsize, CMS_ysize}, -- [space]
		 [3]   = {33, CMS_xsize, CMS_ysize}, -- !
		 [4]   = {35, CMS_xsize, CMS_ysize}, -- #
		 [5]   = {40, CMS_xsize, CMS_ysize}, -- (
		 [6]   = {41, CMS_xsize, CMS_ysize}, -- )
		 [7]   = {42, CMS_xsize, CMS_ysize}, -- *
		 [8]   = {45, CMS_xsize, CMS_ysize}, -- -
		 [9]   = {47, CMS_xsize, CMS_ysize}, -- /
		 [10]  = {48, CMS_xsize, CMS_ysize}, -- 0
		 [11]  = {49, CMS_xsize, CMS_ysize}, -- 1
		 [12]  = {50, CMS_xsize, CMS_ysize}, -- 2
		 [13]  = {51, CMS_xsize, CMS_ysize}, -- 3
		 [14]  = {52, CMS_xsize, CMS_ysize}, -- 4
		 [15]  = {53, CMS_xsize, CMS_ysize}, -- 5
		 [16]  = {54, CMS_xsize, CMS_ysize}, -- 6
		 [17]  = {55, CMS_xsize, CMS_ysize}, -- 7
		 [18]  = {56, CMS_xsize, CMS_ysize}, -- 8
		 [19]  = {57, CMS_xsize, CMS_ysize}, -- 9
		 [20]  = {58, CMS_xsize, CMS_ysize}, -- :
		 [21]  = {63, CMS_xsize, CMS_ysize}, -- ?
		 [22]  = {65, CMS_xsize, CMS_ysize}, -- A
		 [23]  = {66, CMS_xsize, CMS_ysize}, -- B
		 [24]  = {67, CMS_xsize, CMS_ysize}, -- C
		 [25]  = {68, CMS_xsize, CMS_ysize}, -- D
		 [26]  = {69, CMS_xsize, CMS_ysize}, -- E
		 [27]  = {70, CMS_xsize, CMS_ysize}, -- F
		 [28]  = {71, CMS_xsize, CMS_ysize}, -- G
		 [29]  = {72, CMS_xsize, CMS_ysize}, -- H
		 [30]  = {73, CMS_xsize, CMS_ysize}, -- I
		 [31]  = {74, CMS_xsize, CMS_ysize}, -- J
		 [32]  = {75, CMS_xsize, CMS_ysize}, -- K
		 [33]  = {76, CMS_xsize, CMS_ysize}, -- L
		 [34]  = {77, CMS_xsize, CMS_ysize}, -- M
		 [35]  = {78, CMS_xsize, CMS_ysize}, -- N
		 [36]  = {79, CMS_xsize, CMS_ysize}, -- O
		 [37]  = {80, CMS_xsize, CMS_ysize}, -- P
		 [38]  = {81, CMS_xsize, CMS_ysize}, -- Q
		 [39]  = {82, CMS_xsize, CMS_ysize}, -- R
		 [40]  = {83, CMS_xsize, CMS_ysize}, -- S
		 [41]  = {84, CMS_xsize, CMS_ysize}, -- T
		 [42]  = {85, CMS_xsize, CMS_ysize}, -- U
		 [43]  = {86, CMS_xsize, CMS_ysize}, -- V
		 [44]  = {87, CMS_xsize, CMS_ysize}, -- W
		 [45]  = {88, CMS_xsize, CMS_ysize}, -- X
		 [46]  = {89, CMS_xsize, CMS_ysize}, -- Y
		 [47]  = {90, CMS_xsize, CMS_ysize}, -- Z
		 [48]  = {97, CMS_xsize, CMS_ysize}, -- a
		 [49]  = {109,CMS_xsize, CMS_ysize}, -- m
		 [50]  = {115,CMS_xsize, CMS_ysize}, -- s
		 [51]  = {120,CMS_xsize, CMS_ysize}, -- x
		 [52]  = { 46,CMS_xsize, CMS_ysize}} -- .		 
}
