
local TGP_xsize = 50
local TGP_ysize = 70
fontdescription_TGP_Litening_AT = {
	texture    = "Fonts/font_TGP_LITENING_AT.tga",
	size      = {7, 7},
	resolution = {512, 512},
	default    = {TGP_xsize, TGP_ysize},
	chars	    = {
		 [1]  = {32, TGP_xsize, TGP_ysize}, -- [space]
		 [2]  = {42, TGP_xsize, TGP_ysize}, -- *
		 [3]  = {45, TGP_xsize, TGP_ysize}, -- -
		 [4]  = {47, TGP_xsize, TGP_ysize}, -- /
		 [5]  = {48, TGP_xsize, TGP_ysize}, -- 0
		 [6]  = {49, TGP_xsize, TGP_ysize}, -- 1
		 [7]  = {50, TGP_xsize, TGP_ysize}, -- 2
		 [8]  = {51, TGP_xsize, TGP_ysize}, -- 3
		 [9]  = {52, TGP_xsize, TGP_ysize}, -- 4
		 [10]  = {53, TGP_xsize, TGP_ysize}, -- 5
		 [11]  = {54, TGP_xsize, TGP_ysize}, -- 6
		 [12]  = {55, TGP_xsize, TGP_ysize}, -- 7
		 [13]  = {56, TGP_xsize, TGP_ysize}, -- 8
		 [14]  = {57, TGP_xsize, TGP_ysize}, -- 9
		 [15]  = {58, TGP_xsize, TGP_ysize}, -- :
		 [16]  = {60, TGP_xsize, TGP_ysize}, -- <
		 [17]  = {62, TGP_xsize, TGP_ysize}, -- >
		 [18]  = {65, TGP_xsize, TGP_ysize}, -- A
		 [19]  = {66, TGP_xsize, TGP_ysize}, -- B
		 [20]  = {67, TGP_xsize, TGP_ysize}, -- C
		 [21]  = {68, TGP_xsize, TGP_ysize}, -- D
		 [22]  = {69, TGP_xsize, TGP_ysize}, -- E
		 [23]  = {70, TGP_xsize, TGP_ysize}, -- F
		 [24]  = {71, TGP_xsize, TGP_ysize}, -- G
		 [25]  = {72, TGP_xsize, TGP_ysize}, -- H
		 [26]  = {73, TGP_xsize, TGP_ysize}, -- I
		 [27]  = {74, TGP_xsize, TGP_ysize}, -- J
		 [28]  = {75, TGP_xsize, TGP_ysize}, -- K
		 [29]  = {76, TGP_xsize, TGP_ysize}, -- L
		 [30]  = {77, TGP_xsize, TGP_ysize}, -- M
		 [31]  = {78, TGP_xsize, TGP_ysize}, -- N
		 [32]  = {79, TGP_xsize, TGP_ysize}, -- O
		 [33]  = {80, TGP_xsize, TGP_ysize}, -- P
		 [34]  = {81, TGP_xsize, TGP_ysize}, -- Q
		 [35]  = {82, TGP_xsize, TGP_ysize}, -- R
		 [36]  = {83, TGP_xsize, TGP_ysize}, -- S
		 [37]  = {84, TGP_xsize, TGP_ysize}, -- T
		 [38]  = {85, TGP_xsize, TGP_ysize}, -- U
		 [39]  = {86, TGP_xsize, TGP_ysize}, -- V
		 [40]  = {87, TGP_xsize, TGP_ysize}, -- W
		 [41]  = {88, TGP_xsize, TGP_ysize}, -- X
		 [42]  = {89, TGP_xsize, TGP_ysize}, -- Y
		 [43]  = {90, TGP_xsize, TGP_ysize}, -- Z
		 [44]  = {37, TGP_xsize, TGP_ysize}, -- %
		 [45]  = {46, TGP_xsize, TGP_ysize}} -- .
}
