troops = { 
troop('Algerian Air Force', _('Algerian Air Force'), 'AAF.png'),
troop('620th advanced training sq', _('620th advanced training sq'), '620th.png'),
troop('618th advanced training sq', _('618th advanced training sq'), '618th.png'),
troop('123rd Air Defense Sq', _('123rd Air Defense Sq'), '123rd su30.png'),
troop('122nd Air Defense Sq', _('122nd Air Defense Sq'), '122nd su30.png'),
troop('121st Air Defense Sq Su-30', _('121st Air Defense Sq Su-30'), '121st su30.png'),
troop('121st Air Defense Sq Su-33', _('121st Air Defense Sq Su-33'), '121st su33.png'),
troop('121st Air Defense Sq Su-27', _('121st Air Defense Sq Su-27'), '121st su27.png'),
troop('110th Fighting sq', _('110th Fighting sq'), '110th.png'),
troop('52nd Close Air Support sq', _('52nd Close Air Support sq'), '52nd.png'),
troop('12th Air Wing', _('12th Air Wing'), '12thW.png'),
troop('7th Tactical transport Wing', _('7th Tactical transport Wing'), '7W.png'),
troop('6th Maneuver Helicopter Regiment', _('6th Maneuver Helicopter Regiment'), '6thR.png'),
troop('5th FIghter Squadron', _('5th FIghter Squadron'), '5thFS.png'),
troop('4th Squadron of Support and penetration', _('4th Squadron of Support and penetration'), '4thW.png'),
 troop('3rd Air Defense Wing', _('3rd Air Defense Wing'), '3rdW.png'),
troop('2nd Tactical transport Wing', _('2nd Tactical transport Wing'), '2ndW.png'),
troop('1st Combat Helicopter Regiment', _('1st Combat Helicopter Regiment'), '1stR.png'),
troop('Fictional Mirage2000 sq', _('Fictional Mirage2000 sq'), 'm2kaaf.png'),

};
