troops = {
--RAAF
troop('1 SQN RAAF', _('1 SQN RAAF'), '1_SQN_RAAF.png'),
troop('2 SQN RAAF', _('2 SQN RAAF'), '2_SQN_RAAF.png'),
troop('3 SQN RAAF', _('3 SQN RAAF'), '3_SQN_RAAF.png'),
troop('5 SQN RAAF', _('5 SQN RAAF'), '5_SQN_RAAF.png'),
troop('6 SQN RAAF', _('6 SQN RAAF'), '6_SQN_RAAF.png'),
troop('9 SQN RAAF', _('9 SQN RAAF'), '9_SQN_RAAF.png'),
troop('10 SQN RAAF', _('10 SQN RAAF'), '10_SQN_RAAF.png'),
troop('11 SQN RAAF', _('11 SQN RAAF'), '11_SQN_RAAF.png'),
troop('12 SQN RAAF', _('12 SQN RAAF'), '12_SQN_RAAF.png'),
troop('30 SQN RAAF', _('30 SQN RAAF'), '30_SQN_RAAF.png'),
troop('32 SQN RAAF', _('32 SQN RAAF'), '32_SQN_RAAF.png'),
troop('33 SQN RAAF', _('33 SQN RAAF'), '33_SQN_RAAF.png'),
troop('34 SQN RAAF', _('34 SQN RAAF'), '34_SQN_RAAF.png'),
troop('35 SQN RAAF', _('35 SQN RAAF'), '35_SQN_RAAF.png'),
troop('36 SQN RAAF', _('36 SQN RAAF'), '36_SQN_RAAF.png'),
troop('37 SQN RAAF', _('37 SQN RAAF'), '37_SQN_RAAF.png'),
troop('38 SQN RAAF', _('38 SQN RAAF'), '38_SQN_RAAF.png'),
troop('75 SQN RAAF', _('75 SQN RAAF'), '75_SQN_RAAF.png'),
troop('76 SQN RAAF', _('76 SQN RAAF'), '76_SQN_RAAF.png'),
troop('77 SQN RAAF', _('77 SQN RAAF'), '77_SQN_RAAF.png'),
troop('79 SQN RAAF', _('79 SQN RAAF'), '79_SQN_RAAF.png'),
troop('87 SQN RAAF', _('87 SQN RAAF'), '87_SQN_RAAF.png'),
troop('100 SQN RAAF', _('100 SQN RAAF'), '100_SQN_RAAF.png'),
troop('285 SQN RAAF', _('285 SQN RAAF'), '285_SQN_RAAF.png'),
troop('292 SQN RAAF', _('292 SQN RAAF'), '292_SQN_RAAF.png'),
troop('450 SQN RAAF', _('450 SQN RAAF'), '450_SQN_RAAF.png'),
troop('453 SQN RAAF', _('453 SQN RAAF'), '453_SQN_RAAF.png'),
troop('455 SQN RAAF', _('455 SQN RAAF'), '455_SQN_RAAF.png'),
troop('460 SQN RAAF', _('460 SQN RAAF'), '460_SQN_RAAF.png'),
troop('461 SQN RAAF', _('461 SQN RAAF'), '461_SQN_RAAF.png'),
troop('463 SQN RAAF', _('463 SQN RAAF'), '463_SQN_RAAF.png'),
troop('464 SQN RAAF', _('464 SQN RAAF'), '464_SQN_RAAF.png'),
troop('482 SQN RAAF', _('482 SQN RAAF'), '482_SQN_RAAF.png'),
troop('486 SQN RAAF', _('486 SQN RAAF'), '486_SQN_RAAF.png'),
troop('492 SQN RAAF', _('492 SQN RAAF'), '492_SQN_RAAF.png'),
troop('41 WING RAAF', _('41 WING RAAF'), '41WingRAAF.png'),
troop('42 WING RAAF', _('42 WING RAAF'), '42WingRAAF.png'),
troop('44 WING RAAF', _('44 WING RAAF'), '44WingRAAF.png'),
troop('78 WING RAAF', _('78 WING RAAF'), '78WingRAAF.png'),
troop('81 WING RAAF', _('81 WING RAAF'), '81WingRAAF.png'),
troop('82 WING RAAF', _('82 WING RAAF'), '82WingRAAF.png'),
troop('84 WING RAAF', _('84 WING RAAF'), '84WingRAAF.png'),
troop('86 WING RAAF', _('86 WING RAAF'), '86WingRAAF.png'),
troop('92 WING RAAF', _('92 WING RAAF'), '92WingRAAF.png'),
troop('AIR TRAINING WING RAAF', _('Air Training Wing RAAF'), 'ATWingRAAF.png'),
troop('HEALTH SERVICES WING RAAF', _('Health Services Wing RAAF'), 'HSWingRAAF.png'),
troop('302 AIR BASE WING RAAF', _('302 Air Base Wing RAAF'), '302ABWingRAAF.png'),
troop('303 AIR BASE WING RAAF', _('303 Air Base Wing RAAF'), '303ABWingRAAF.png'),
troop('304 AIR BASE WING RAAF', _('304 Air Base Wing RAAF'), '304ABWingRAAF.png'),
troop('395 EXPEDITIONARY COMBAT SUPPORT WING RAAF', _('395 Expeditionary Combat Support Wing RAAF'), '395ExSupRAAF.png'),
troop('501 WING RAAF', _('501 WING RAAF'), '501WingRAAF.png'),
troop('503 WING RAAF', _('503 WING RAAF'), '503WingRAAF.png'),

--ARMY
troop('1st AVIATION REGIMENT', _('1st AVIATION REGIMENT'), '1st_Aviation_Regiment.png'),
troop('5th AVIATION REGIMENT', _('5th AVIATION REGIMENT'), '5th_Aviation_Regiment.png'),
troop('6th AVIATION REGIMENT', _('6th AVIATION REGIMENT'), '6th_Aviation_Regiment.png'),
troop('AUST AVIATION CORPS', _('AUST AVIATION CORPS'), 'Australian_Aviation_Corp.png'),
};