troops = {
    troop("PLAAF 1st Division", _("PLAAF 1st Division"), "plaaf_1st.png"),
	troop("PLAAF 2nd Division", _("PLAAF 2nd Division"), "plaaf_2nd.png"),
	troop("PLAAF 3rd Division", _("PLAAF 3rd Division"), "plaaf_fighter.png"),
	troop("PLAAF 4th Division", _("PLAAF 4th Division"), "plaaf_trans.png"),
	troop("PLAAF 5th Division", _("PLAAF 5th Division"), "plaaf_fighter.png"),
	troop("PLAAF 6th Division", _("PLAAF 6th Division"), "plaaf_6th.png"),
	troop("PLAAF 7th Division", _("PLAAF 7th Division"), "plaaf_fighter.png"),
	troop("PLAAF 8th Division", _("PLAAF 8th Division"), "plaaf_bomber.png"),
	troop("PLAAF 9th Division", _("PLAAF 9th Division"), "plaaf_fighter.png"),
	troop("PLAAF 10th Division", _("PLAAF 10th Division"), "plaaf_bomber.png"),
	troop("PLAAF 11th Division", _("PLAAF 11th Division"), "plaaf_11th.png"),
	troop("PLAAF 12th Division", _("PLAAF 12th Division"), "plaaf_12th.png"),
	troop("PLAAF 13th Division", _("PLAAF 13th Division"), "plaaf_trans.png"),
	troop("PLAAF 14th Division", _("PLAAF 14th Division"), "plaaf_fighter.png"),
	troop("PLAAF 15th Division", _("PLAAF 15th Division"), "plaaf_fighter.png"),
	troop("PLAAF 16th Division", _("PLAAF 16th Division"), "plaaf_fighter.png"),
	troop("PLAAF 18th Division", _("PLAAF 18th Division"), "plaaf_18th.png"),
	troop("PLAAF 19th Division", _("PLAAF 19th Division"), "plaaf_19th.png"),
	troop("PLAAF 20th Division", _("PLAAF 20th Division"), "plaaf_fighter.png"),
	troop("PLAAF 21st Division", _("PLAAF 21st Division"), "plaaf_21st.png"),
	troop("PLAAF 24th Division", _("PLAAF 24th Division"), "plaaf_fighter.png"),
	troop("PLAAF 28th Division", _("PLAAF 28th Division"), "plaaf_fighter.png"),	
	troop("PLAAF 33rd Division", _("PLAAF 33rd Division"), "plaaf_33rd.png"),
	troop("PLAAF 36th Division", _("PLAAF 36th Division"), "plaaf_bomber.png"),	
	troop("PLAAF 44th Division", _("PLAAF 44th Division"), "plaaf_fighter.png"),
	troop("PLAAF Flight & Test Training Base", _("PLAAF Flight & Test Training Base"), "plaaf_fttb.png"),
	troop("PLANAF 2nd Division", _("PLANAF 2nd Division"), "plana.png"),
	troop("PLANAF 4th Division", _("PLANAF 4th Division"), "plana.png"),
	troop("PLANAF 5th Division", _("PLANAF 5th Division"), "plana.png"),
	troop("PLANAF 6th Division", _("PLANAF 6th Division"), "plana.png"),
	troop("PLANAF 8th Division", _("PLANAF 8th Division"), "plana.png"),
	troop("PLANAF 9th Division", _("PLANAF 9th Division"), "plana.png"),
	troop("PLA Army Aviation", _("PLA Army Aviation"), "plaaa.png"),
};
