troops = {
--AERONAUTICA
    troop('Section Break', _('*AERONAUTICA*'), 'AMI.png'),
    troop('2stormo', '2° '.._('STORMO'), '2stormo.png'), 
    troop('3stormo', '3° '.._('STORMO'), '3stormo.png'),
    troop('4stormo', '4° '.._('STORMO'), '4stormo.png'),
    troop('5stormo', '5° '.._('STORMO'), '5stormo.png'),
    troop('6stormo', '6° '.._('STORMO'), '6stormo.png'),
    troop('8stormo', '8° '.._('STORMO'), '8stormo.png'),
    troop('9stormo', '9° '.._('STORMO'), '9stormo.png'),
    troop('14stormo', '14° '.._('STORMO'), '14stormo.png'),
    troop('15stormo', '15° '.._('STORMO'), '15stormo.png'),
    troop('30stormo', '30° '.._('STORMO'), '30stormo.png'),
    troop('31stormo', '31° '.._('STORMO'), '31stormo.png'),
    troop('32stormo', '32° '.._('STORMO'), '32stormo.png'),
    troop('36stormo', '36° '.._('STORMO'), '36stormo.png'),
    troop('37stormo', '37° '.._('STORMO'), '37stormo.png'),
    troop('41stormo', '41° '.._('STORMO'), '41stormo.png'),
    troop('46ba', '46° '.._('Brigata Aerea'), '46ba.png'),
    troop('50stormo', '50° '.._('STORMO'), '50stormo.png'),
    troop('51stormo', '51° '.._('STORMO'), '51stormo.png'),
    troop('53stormo', '53° '.._('STORMO'), '53stormo.png'),
    troop('61stormo', '61° '.._('STORMO'), '61stormo.png'),
    troop('70stormo', '70° '.._('STORMO'), '70stormo.png'),
    troop('72stormo', '72° '.._('STORMO'), '72stormo.png'),
    troop('RSV', _('Reparto Sperimentale Volo'), 'RSV.png'),
    troop('Frecce Tricolori', _('Frecce Tricolori'), 'FrecceTricolori.png'),
--MARINA
    troop('Section Break', _('*MARINA*'), 'MMI.png'),
    troop('Harrier', _('HarrierII+ Groupaer'), 'MARINA_harrier.png'),
};
