troops = {
    troop('344 TsBP Torzhok', _('344 TsBP Torzhok'), 'TsBP_Torzhok.png'),
    troop('Kamov Test Pilot', _('Kamov Test Pilot'), 'Test_pilot.png'),
    troop('Golden Eagles', _('Golden Eagles'), 'Berkuty.png'),
    troop('Army Aviation', _('Army Aviation'), 'Armeiskaya_Aviatsiya.png'),
    troop('Land Forces', _('Land Forces'), 'Aviatsiya_sukhoputnykh_voisk.png'),
    troop('AA Headquarters', _('AA Headquarters'), 'Upravlenie_armeiskoy_aviatsii.png'),
    troop('MVO Headquarters', _('MVO Headquarters'), 'Aviatsia_MVO_upravlenie.png'),
    troop('Ryazan BVP', _('Ryazan BVP'), 'Aviatsiya_sukhoputnikh_voisk_BVP_Razan.png'),
    troop('45 OVP', _('45 OVP'), '45-OVP_MVO.png'),
    troop('288 OVP', _('288 OVP'), '288-OVP.png'),
    troop('332 OGVP', _('332 OGVP'), '332-OGVP.png'),
    troop('440 OVP', _('440 OVP'), '440-OVP_MVO.png'),
    troop('490 OVP', _('490 OVP'), '490-OVP_MVO.png'),
    troop('762 OBS', _('762 OBS'), '762-OBS_MVO.png'),
    troop('865 BRV', _('865 BRV'), '865-BRV_MVO.png'),
    troop('Russian Air Force', _('Russian Air Force'), 'Rus-Airforce.png'),
    troop('14th Regiment', _('14th Regiment'), '14_IAP.png'),
    troop('28th Regiment', _('28th Regiment'), '28_IAP.png'),
    troop('159th Regiment', _('159th Regiment'), '159_IAP.png'),
    troop('177th Regiment', _('177th Regiment'), '177_IAP.png'),
    troop('611th Regiment', _('611th Regiment'), '611_IAP.png'),
    troop('689th Regiment', _('689th Regiment'), '689_IAP.png'),
    troop('279th Regiment', _('279th Regiment'), 'KIAP.png'),
    troop('"Russian Knights" group', _('"Russian Knights" group'), 'Russian-Knights.png'),
    troop('"Swifts" group', _('"Swifts" group'), 'Swifts.png'),
};
