troops = {
--SPANISH AIR FORCE
    troop('Section Break', _('*SPANISH AIR FORCE*'), 'spanishairforce.png'),
    troop('11 Wing', _('11 Wing (Eurofighter)'), 'ala11.png'),
	troop('111 Squadron', _('111 Squadron'), 'escuadron111.png'),
	troop('113 Squadron', _('113 Squadron'), 'escuadron113.png'),
	troop('12 Wing', _('12 Wing (F-18)'), 'ala12.png'),
	troop('121 Squadron', _('121 Squadron'), 'escuadron121.png'),
	troop('122 Squadron', _('122 Squadron'), 'escuadron122.png'),
	troop('14 Wing', _('14 Wing (F-1, Eurofighter)'), 'ala14.png'),
	troop('141 Squadron', _('141 Squadron'), '141.png'),
	troop('142 Squadron', _('142 Squadron'), '142.png'),
	troop('15 Wing', _('15 Wing (F-18)'), 'ala15.png'),
	troop('151 Squadron', _('151 Squadron'), 'escuadron151.png'),
	troop('152 Squadron', _('152 Squadron'), 'escuadron152.png'),
	troop('153 Squadron', _('153 Squadron'), 'escuadron153.png'),
	troop('23 Wing', _('23 Wing (F-5)'), 'ala23.png'),
	troop('31 Wing', _('31 Wing (C-130)'), 'ala31.png'),
	troop('46 Wing', _('46 Wing (F-18)'), 'ala46.png'),
	troop('Spanish Air Force Academy', _('Spanish Air Force Academy'), 'AGA.png'),
	troop('Aguila Patrol', _('Aguila Patrol'), 'patrulla_aguila.png'),
	--FAMET
    troop('Section Break', _('*FAMET*'), 'FAMET.png'),
	troop('BHELA I (19xx-1995)', _('BHELA I (19xx-1995)'), 'BHELAI-19xx-1995.png'),
	troop('BHELA I (1995-)', _('BHELA I (1995-)'), 'BHELAI-1995-.png'),
	troop('BHELA I 1st Co.', _('BHELA I 1st Co.'), '1ciaBHELAI.png'),
	troop('BHELA I 1st Co. Tigre', _('BHELA I 1st Co. Tigre'), '1ciaBHELAI-tigre.png'),
	troop('BHELA I 3rd Co.', _('BHELA I 3rd Co.'), '3ciaBHELAI.png'),
	troop('BHELA I Attack pilot', _('BHELA I Attack pilot'), 'piloto-ataque-bhela1.png'),
	troop('BHELMA II Sahara', _('BHELMA II Sahara'), 'BHELMAII-sahara.png'),
	troop('BHELEME II Sahara', _('BHELEME II Sahara'), 'BHELEMEII-sahara.png'),
	troop('II Helicopters Unit (71-74)', _('II Helicopters Unit (71-74)'), 'UHELII.png'),
	troop('BHELMA II (1992-1994)', _('BHELMA II (1992-1994)'), 'BHELMAII-92-94.png'),
	troop('BHELMA II Si quieres puedes', _('BHELMA II Si quieres puedes'), 'BHELMAII-sqp.png'),
	troop('BHELMA II Nuevos camellos', _('BHELMA II Nuevos camellos'), 'BHELMAII-nc.png'),
	troop('BHELMA III', _('BHELMA III'), 'BHELMAIII.png'),
	troop('BHELMA IV', _('BHELMA IV'), 'BHELMAIV.png'),
	troop('BHELTRA V 1st Co.', _('BHELTRA V 1st Co.'), 'bheltraV-1cia.png'),
	troop('BHELMA VI Combat crew member', _('BHELMA VI Combat crew member'), 'tripulante_BHELMAVI.png'),
	troop('UH-1N and UH-1H pilot', _('UH-1N and UH-1H pilot'), 'piloto_UH-1N_y_UH-1H.png'),
	troop('Coronel Mate Base', _('Coronel Mate Base'), 'coronel-mate.png'),
	--SPANISH NAVY
    troop('Section Break', _('*SPANISH NAVY*'), 'armada.png'),
	troop('Third Escuadrilla', _('Third Escuadrilla'), '3escuadrilla.png'),
	troop('3rd Esc. El gato con botas', _('3rd Esc. El gato con botas'), '3escuadrilla-gatoconbotas.png'),
	troop('Fourth Escuadrilla', _('Fourth Escuadrilla'), '4escuadrilla.png'),
	troop('Fifth Escuadrilla', _('Fifth Escuadrilla'), '5escuadrilla.png'),
	troop('5th Esc. Amphibious assault CSAR', _('5th Esc. Amphibious assault CSAR'), '5escuadrilla-csar.png'),
	troop('Sixth Escuadrilla', _('Sixth Escuadrilla'), '6escuadrilla.png'),
	troop('Eighth Escuadrilla (desactivada)', _('Eighth Escuadrilla (deactivated)'), '8escuadrilla.png'),
	troop('Ninth Escuadrilla', _('Ninth Escuadrilla'), '9escuadrilla.png'),
	troop('9th Escuadrilla Fighter and attack', _('9th Escuadrilla Fighter and attack'), '9cazayataque.png'),
	troop('9th Escuadrilla Harrier II', _('9th Escuadrilla Harrier II'), 'harrierII.png'),
	troop('9th Escuadrilla Cobra', _('9th Escuadrilla Cobra'), '9escuadrilla-cobra.png'),
	troop('Tenth Escuadrilla', _('Tenth Escuadrilla'), '10escuadrilla.png'),
	troop('10th Escuadrilla Armed Helo', _('10th Escuadrilla Armed Helo'), '10-armed-helo.png'),
	troop('10th Escuadrilla Plane captain', _('10th Escuadrilla Plane captain'), '10-plane-captain.png'),
};
