-- Weapons' types definitions
-- Copyright (C) 2004, Eagle Dynamics.
-- the file is not intended for an end-user editing
-- level 1

wstype_bombs[2]   = {wsType_Weapon, wsType_Bomb, wsType_Bomb_BetAB} -- BetAB_250
wstype_bombs[3]   = {wsType_Weapon, wsType_Bomb, wsType_Bomb_BetAB} -- BetAB_500
wstype_bombs[4]   = {wsType_Weapon, wsType_Bomb, wsType_Bomb_BetAB} -- BetAB_500ShP
wstype_bombs[5]   = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- FAB_100
wstype_bombs[6]   = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- FAB_250
wstype_bombs[7]   = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- FAB_500
wstype_bombs[9]   = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- FAB_1500
wstype_bombs[11]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- KAB_500
wstype_bombs[12]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- KAB_500Kr
wstype_bombs[13]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- KAB_500KrOD
wstype_bombs[14]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- KAB_1500Kr
wstype_bombs[15]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- KMGU_2f
wstype_bombs[16]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_ODAB} -- ODAB_500PM
wstype_bombs[18]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- RBK_250
wstype_bombs[19]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- RBK_250S
wstype_bombs[20]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- RBK_500AO
wstype_bombs[21]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- RBK_500SOAB
wstype_bombs[22]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- Puma
wstype_bombs[23]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- BL_755
wstype_bombs[24]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Antisubmarine} -- GluB
wstype_bombs[26]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_BetAB} -- NB_2
wstype_bombs[27]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Antisubmarine} -- Torpedo
wstype_bombs[29]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Fire} -- XZAB_500
wstype_bombs[30]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- Mk_81
wstype_bombs[31]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- Mk_82
wstype_bombs[32]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- Mk_83
wstype_bombs[33]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- Mk_84
wstype_bombs[34]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- M_117
wstype_bombs[35]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- CBU_97
wstype_bombs[36]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- GBU_10
wstype_bombs[38]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- GBU_12
wstype_bombs[39]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- GBU_16
wstype_bombs[41]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- GBU_24
wstype_bombs[42]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- GBU_15
wstype_bombs[43]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- GBU_27
wstype_bombs[44]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- GBU_22
wstype_bombs[45]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- ROCKEYE
wstype_bombs[47]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- AGM_62
wstype_bombs[48]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- GBU_28
wstype_bombs[54]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- FAB_250P
wstype_bombs[55]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- FAB_500P
wstype_bombs[56]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- FAB_500_3
wstype_bombs[57]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- MW_1
wstype_bombs[58]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- PB_250
wstype_bombs[59]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Fire} -- Z_BAK_3
wstype_bombs[60]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- KMGU_2b
wstype_bombs[61]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Antisubmarine} -- Mk_50_Torpedo
wstype_bombs[62]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_BetAB} -- Durandal
wstype_bombs[63]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Lighter} -- SAB_100
wstype_bombs[64]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Lighter} -- LUU_2
wstype_bombs[65]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- AO_2_5RT
wstype_bombs[66]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A} -- PTAB_2_5KO

wstype_bombs[69]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A}  -- BDU_33
wstype_bombs[70]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A}  -- BDU_50LD
wstype_bombs[71]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A}  -- BDU_50HD
wstype_bombs[72]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided} -- BDU_50LGB
wstype_bombs[75]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A}  -- MK_82AIR
wstype_bombs[77]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster} -- CBU_87
wstype_bombs[79]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_A}  -- MK_82SNAKEYE}


wstype_bombs[85]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided, GBU_31}
wstype_bombs[86]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Guided, GBU_38}
wstype_bombs[87]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster, CBU_105} --CBU_105
wstype_bombs[88]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster, CBU_103} --CBU_103 
wstype_bombs[89]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster, CBU_104} --CBU_104 

wstype_bombs[91]  = {wsType_Weapon, wsType_Bomb, wsType_Bomb_Cluster, RBK_500U} --RBK_500U 

wstype_missiles[1]   = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- R_550
wstype_missiles[2]   = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- MICA_T
wstype_missiles[3]   = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- MICA_R
wstype_missiles[4]   = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- Super_530D
wstype_missiles[7]   = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_40R
wstype_missiles[9]   = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_24R
wstype_missiles[10]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_60
wstype_missiles[11]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_33E
wstype_missiles[12]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_27AE
wstype_missiles[13]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_27P
wstype_missiles[14]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_27PE
wstype_missiles[15]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_27T
wstype_missiles[16]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_27TE
wstype_missiles[17]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_27EM
wstype_missiles[18]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_73
wstype_missiles[19]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_77
wstype_missiles[20]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_37
wstype_missiles[21]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- AIM_7
wstype_missiles[22]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- AIM_9
wstype_missiles[23]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- AIM_54
wstype_missiles[24]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- AIM_120
wstype_missiles[26]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_24T
wstype_missiles[27]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- P_40T
wstype_missiles[28]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- SeaSparrow
wstype_missiles[30]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- C_8CM
wstype_missiles[31]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- C_5
wstype_missiles[32]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- C_8
wstype_missiles[33]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- C_13
wstype_missiles[34]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- C_24
wstype_missiles[35]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- C_25
wstype_missiles[36]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- HYDRA_70
wstype_missiles[37]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- Zuni_127
wstype_missiles[38]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- Zuni_127CM
wstype_missiles[39]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_114K
wstype_missiles[40]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_119
wstype_missiles[41]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_22
wstype_missiles[42]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_29TE
wstype_missiles[43]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_23
wstype_missiles[44]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_28
wstype_missiles[45]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_25ML
wstype_missiles[46]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_58
wstype_missiles[47]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_25MP
wstype_missiles[48]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AT_6
wstype_missiles[49]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_29L
wstype_missiles[50]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_55
wstype_missiles[51]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_65
wstype_missiles[52]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_15
wstype_missiles[53]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_31A
wstype_missiles[54]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_59M
wstype_missiles[55]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_35
wstype_missiles[56]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_41
wstype_missiles[57]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- Vikhr
wstype_missiles[58]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- Vikhr_M
wstype_missiles[59]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_114
wstype_missiles[60]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_45
wstype_missiles[61]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_65K
wstype_missiles[62]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_84A
wstype_missiles[63]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_84E
wstype_missiles[64]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_86
wstype_missiles[65]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_88
wstype_missiles[66]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- Sea_Eagle
wstype_missiles[67]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SAV611
wstype_missiles[68]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_122
wstype_missiles[69]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_123
wstype_missiles[70]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_65E
wstype_missiles[71]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_130
wstype_missiles[72]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- ALARM
wstype_missiles[73]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_23L
wstype_missiles[74]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_25MR
wstype_missiles[75]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_29T
wstype_missiles[76]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- X_31P
wstype_missiles[77]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_65D
wstype_missiles[78]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- Kormoran
wstype_missiles[79]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SM_2
wstype_missiles[80]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA5B55
wstype_missiles[81]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA48H6E2
wstype_missiles[82]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA9M82
wstype_missiles[83]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA9M83
wstype_missiles[84]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA3M9M
wstype_missiles[85]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA9M33
wstype_missiles[86]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA9M31
wstype_missiles[87]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA9M38M1
wstype_missiles[88]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA9M333
wstype_missiles[89]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA9M330
wstype_missiles[90]  = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- SA9M311
wstype_missiles[91]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- Igla_1E
wstype_missiles[92]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- MIM_104
wstype_missiles[93]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- FIM_92C
wstype_missiles[94]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- GRAD_RAKETA
wstype_missiles[URAGAN_9M27F] = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- URAGAN_RAKETA
wstype_missiles[95]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- SMERCH_RAKETA
wstype_missiles[SMERCH_9M55F] = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- SMERCH_9M55F
wstype_missiles[97]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- SA5B27
wstype_missiles[98]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- HAWK_RAKETA
wstype_missiles[99]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- ROLAND_R
wstype_missiles[118] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- P_35
wstype_missiles[119] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- P_500
wstype_missiles[120] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- P_700
wstype_missiles[121] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- P_15U
wstype_missiles[122] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- P_120
wstype_missiles[123] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- R_85
wstype_missiles[124] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- R_85U
wstype_missiles[125] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- BGM_109B
wstype_missiles[96]  = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- SCUD_RAKETA
wstype_missiles[126] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- AGM_84S
wstype_missiles[127] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- MALUTKA
wstype_missiles[128] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- KONKURS
wstype_missiles[129] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- P_9M117
wstype_missiles[130] = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- TOW
wstype_missiles[131] = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- M26_RAKETA
wstype_missiles[132] = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_154
wstype_missiles[133] = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- S_25L
wstype_missiles[134] = {wsType_Weapon, wsType_Shell, wsType_Shell_A} -- wsType_Shell_SPPU
wstype_missiles[135]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- AIM_9P
wstype_missiles[136]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- AIM_9X
wstype_missiles[137]  = {wsType_Weapon, wsType_Missile, wsType_SA_Missile} -- MIM_72
wstype_missiles[106]  = {wsType_Weapon, wsType_Missile, wsType_AA_Missile} -- AIM_120C
-- A-10C weapons
wstype_missiles[138]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_65H
wstype_missiles[139]  = {wsType_Weapon, wsType_Missile, wsType_AS_Missile} -- AGM_65G
wstype_missiles[140]  = {wsType_Weapon, wsType_Missile, wsType_AS_TRAIN_Missile} -- TGM_65G
wstype_missiles[141]  = {wsType_Weapon, wsType_Missile, wsType_AS_TRAIN_Missile} -- TGM_65D
wstype_missiles[CATM_65K]  = {wsType_Weapon, wsType_Missile, wsType_AA_TRAIN_Missile} -- CATM_65K
wstype_missiles[CATM_9]  = {wsType_Weapon, wsType_Missile, wsType_AA_TRAIN_Missile} -- CATM_9
wstype_missiles[TGM_65H] = {wsType_Weapon, wsType_Missile, wsType_AS_TRAIN_Missile} --TGM_65H
wstype_missiles[156] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- P_9M119 Reflex
wstype_missiles[157] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- P_9M119 Svir
--wstype_missiles[158]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- C_8FP2
wstype_missiles[158]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- C_8OM
--wstype_missiles[159]  = {wsType_Weapon, wsType_NURS, wsType_Rocket} -- HVAR
wstype_missiles[160] = {wsType_Weapon, wsType_Missile, wsType_SS_Missile} -- TOW2

wstype_containers[1]   = {wsType_Weapon, wsType_NURS, wsType_Container} -- UB_13
wstype_containers[2]   = {wsType_Weapon, wsType_NURS, wsType_Container} -- UB_32_1
wstype_containers[3]   = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MBD_3
wstype_containers[4]   = {wsType_Weapon, wsType_GContainer, wsType_Support} -- LAU_88
wstype_containers[5]   = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_3000
wstype_containers[6]   = {wsType_Weapon, wsType_NURS, wsType_Container} -- B_20
wstype_containers[7]   = {wsType_Weapon, wsType_NURS, wsType_Container} -- S_25_C
wstype_containers[8]   = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU_10
wstype_containers[9]   = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU_61
wstype_containers[10]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F_15_PTB
wstype_containers[11]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F_16_PTB_N1
wstype_containers[12]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F_16_PTB_N2
wstype_containers[13]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F_18_PTB
wstype_containers[14]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- MIG_23_PTB
wstype_containers[15]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- MIG_25_PTB
wstype_containers[16]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_1150
wstype_containers[17]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_1500
wstype_containers[18]  = {wsType_Weapon, wsType_GContainer, wsType_Cannon_Cont} -- SPPU_22
wstype_containers[19]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- KINGAL
wstype_containers[20]  = {wsType_Weapon, wsType_GContainer, wsType_Cannon_Cont} -- UPK_23_25
wstype_containers[21]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MBD
wstype_containers[22]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MBD_4
wstype_containers[23]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- TU_22_MBD
wstype_containers[24]  = {wsType_Weapon, wsType_NURS, wsType_Container} -- S_25_PU
wstype_containers[25]  = {wsType_Weapon, wsType_GContainer, wsType_Jam_Cont} -- ALQ_131
wstype_containers[26]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- LANTIRN
wstype_containers[27]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- LANTIRN_F18
wstype_containers[28]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- PAVETACK
wstype_containers[29]  = {wsType_Weapon, wsType_GContainer, wsType_Jam_Cont} -- SORBCIJA
wstype_containers[30]  = {wsType_Weapon, wsType_GContainer, wsType_Jam_Cont} -- SPS_141
wstype_containers[32]  = {wsType_Weapon, wsType_NURS, wsType_Container} -- MBD_3_LAU_10
wstype_containers[33]  = {wsType_Weapon, wsType_NURS, wsType_Container} -- MBD_3_LAU_61
wstype_containers[34]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- AT_9M120
wstype_containers[35]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- AT_9M120M
wstype_containers[36]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F_5_PTB
wstype_containers[37]  = {wsType_Weapon, wsType_GContainer, wsType_Jam_Cont} -- Sky_Shadow
wstype_containers[38]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_F2_1500
wstype_containers[39]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- M2000_PTB
wstype_containers[MBD_A10_2]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MBD_A10_2
wstype_containers[41]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F4_PTB_WING
wstype_containers[42]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F4_PTB_FUZ
wstype_containers[43]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- AGM_114_Pilon
wstype_containers[44]  = {wsType_Weapon, wsType_Missile, wsType_Container} -- AT_6_9M114
wstype_containers[45]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- F4_PILON
wstype_containers[46]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MER_L_P_60
wstype_containers[47]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MER_R_P_60
wstype_containers[48]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MER_TOW
wstype_containers[49]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MER_2_F_18
wstype_containers[50]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MER_9_B52
wstype_containers[51]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MER_12_B52
wstype_containers[52]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MBD_6_B52
wstype_containers[53]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_2000
wstype_containers[54]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_800L_Wing
wstype_containers[55]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_S_3
wstype_containers[56]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_367GAL
wstype_containers[57]  = {wsType_Weapon, wsType_GContainer, wsType_Jam_Cont} -- SKY_SHADOW
wstype_containers[58]  = {wsType_Weapon, wsType_GContainer, wsType_Snare_Cont} -- BOZ_100
wstype_containers[59]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- LANTIRN_F14
wstype_containers[60]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- FLIR_POD
wstype_containers[61]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB_1150_29
wstype_containers[62]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- TANGAZH
wstype_containers[63]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- EPHIR
wstype_containers[64]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- SHPIL
wstype_containers[65]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- FANTASM
wstype_containers[66]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGenerator_red
wstype_containers[67]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGeneratorAIM_red
wstype_containers[68]  = {wsType_Weapon, wsType_NURS, wsType_Container} -- B_20CM
wstype_containers[69]  = {wsType_Weapon, wsType_NURS, wsType_Container} -- Whiskey_Pete
wstype_containers[70]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- SUU_25
wstype_containers[71]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F_18A_PTB
wstype_containers[72]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- F_18C_PTB
wstype_containers[73]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MBD_2
wstype_containers[74]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- AN_AAS_38_FLIR
wstype_containers[75]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- APU_6_VIKHR
wstype_containers[76]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MBD_2_67U
wstype_containers[77]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- S-25L_AND_PU
wstype_containers[78]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- AN_ASQ_173_LST_CAM
wstype_containers[79]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- LAU_118A
wstype_containers[80]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- AKU_58
wstype_containers[81]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- KMGU_2
wstype_containers[82]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGenerator_green
wstype_containers[83]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGenerator_blue
wstype_containers[84]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGenerator_white
wstype_containers[85]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGenerator_yellow
wstype_containers[86]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGenerator_orange
wstype_containers[87]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGeneratorAIM_green
wstype_containers[88]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGeneratorAIM_blue
wstype_containers[89]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGeneratorAIM_white
wstype_containers[90]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGeneratorAIM_yellow
wstype_containers[91]  = {wsType_Weapon, wsType_GContainer, wsType_Smoke_Cont} -- SmokeGeneratorAIM_orange
wstype_containers[92]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- APU_68
wstype_containers[93]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- APU_73
wstype_containers[94]  = {wsType_Weapon, wsType_GContainer, wsType_Jam_Cont} -- MPS_410
wstype_containers[95]  = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- Kopyo
wstype_containers[96]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- APU_170
wstype_containers[97]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- LAU_117
wstype_containers[98]  = {wsType_Weapon, wsType_NURS, wsType_Container} -- B_8V20A
wstype_containers[99]  = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- PTB-KA-50
wstype_containers[100] = {wsType_Weapon, wsType_GContainer, wsType_Support} -- APU_8_9M114
wstype_containers[101] = {wsType_Weapon, wsType_GContainer, wsType_Control_Cont} -- AN/AAQ-28 LITENING
wstype_containers[142]  = {wsType_Weapon, wsType_GContainer, wsType_Jam_Cont} -- ALQ_184
wstype_containers[TER_LS] = {wsType_Weapon, wsType_GContainer, wsType_Support} -- TER container
wstype_containers[TK600] = {wsType_Air, wsType_Free_Fall, wsType_FuelTank} -- Fuel Tank A-10 FT600
wstype_containers[OH_58_BRAUNING]  = {wsType_Weapon, wsType_GContainer, wsType_Cannon_Cont} -- OH-58 brauning
wstype_containers[LAU_131]  = {wsType_Weapon, wsType_NURS, wsType_Container} -- M260
wstype_containers[LAU_131WP]  = {wsType_Weapon, wsType_NURS, wsType_Container} -- M260
wstype_containers[B_8V20A_WP] = {wsType_Weapon, wsType_NURS, wsType_Container} -- B-8V20 with S-8CM
wstype_containers[B_8V20A_OFP2] = {wsType_Weapon, wsType_NURS, wsType_Container} -- B-8V20 with S-8OFP2
wstype_containers[B_8V20A_OM] = {wsType_Weapon, wsType_NURS, wsType_Container} -- B-8V20 with S-8CM
wstype_containers[B_8M1_OFP2] = {wsType_Weapon, wsType_NURS, wsType_Container} -- B-8M1 with S-8OFP2
wstype_containers[TRAVEL_POD] = {wsType_Weapon, wsType_GContainer, wsType_Support} -- MXU-648 Travel Pod
wstype_containers[SUU_25x3]  = {wsType_Weapon, wsType_GContainer, wsType_Support} -- TER 3 * SUU_25


wstype_containers[LAU_68_HYDRA_70_MK1] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with Mk1
wstype_containers[LAU_68_HYDRA_70_MK5] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with Mk5 
wstype_containers[LAU_68_HYDRA_70_MK61] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with Mk61 
wstype_containers[LAU_68_HYDRA_70_M151] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with Mk151 
wstype_containers[LAU_68_HYDRA_70_M156] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with Mk156 
wstype_containers[LAU_68_HYDRA_70_WTU1B] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with WTU1B 
wstype_containers[LAU_68_HYDRA_70_M257] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with M257 
wstype_containers[LAU_68_HYDRA_70_M274] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with M274
wstype_containers[LAU_68_HYDRA_70_M278] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68 with M278

wstype_containers[LAU_131_HYDRA_70_MK1] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with Mk1
wstype_containers[LAU_131_HYDRA_70_MK5] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with Mk5 
wstype_containers[LAU_131_HYDRA_70_MK61] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with Mk61 
wstype_containers[LAU_131_HYDRA_70_M151] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with Mk151 
wstype_containers[LAU_131_HYDRA_70_M156] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with Mk156 
wstype_containers[LAU_131_HYDRA_70_WTU1B] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with WTU1B 
wstype_containers[LAU_131_HYDRA_70_M257] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with M257 
wstype_containers[LAU_131_HYDRA_70_M274] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with M274
wstype_containers[LAU_131_HYDRA_70_M278] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with M278

wstype_containers[LAU_68x3_HYDRA_70_MK1] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with Mk1
wstype_containers[LAU_68x3_HYDRA_70_MK5] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with Mk5 
wstype_containers[LAU_68x3_HYDRA_70_MK61] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with Mk61 
wstype_containers[LAU_68x3_HYDRA_70_M151] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with Mk151 
wstype_containers[LAU_68x3_HYDRA_70_M156] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with Mk156 
wstype_containers[LAU_68x3_HYDRA_70_WTU1B] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with WTU1B 
wstype_containers[LAU_68x3_HYDRA_70_M257] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with M257 
wstype_containers[LAU_68x3_HYDRA_70_M274] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with M274
wstype_containers[LAU_68x3_HYDRA_70_M278] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with M278

wstype_containers[LAU_131x3_HYDRA_70_MK1] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-131 with Mk1
wstype_containers[LAU_131x3_HYDRA_70_MK5] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with Mk5 
wstype_containers[LAU_131x3_HYDRA_70_MK61] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with Mk61 
wstype_containers[LAU_131x3_HYDRA_70_M151] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with Mk151 
wstype_containers[LAU_131x3_HYDRA_70_M156] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with Mk156 
wstype_containers[LAU_131x3_HYDRA_70_WTU1B] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with WTU1B 
wstype_containers[LAU_131x3_HYDRA_70_M257] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with M257 
wstype_containers[LAU_131x3_HYDRA_70_M274] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with M274
wstype_containers[LAU_131x3_HYDRA_70_M278] = {wsType_Weapon, wsType_NURS, wsType_Container} -- LAU-68x3 with M278

wstype_containers[XM_158_HYDRA_70_MK1] 		= {wsType_Weapon, wsType_NURS, wsType_Container} 
wstype_containers[XM_158_HYDRA_70_MK5] 		= {wsType_Weapon, wsType_NURS, wsType_Container} 
wstype_containers[XM_158_HYDRA_70_M151] 	= {wsType_Weapon, wsType_NURS, wsType_Container} 
wstype_containers[XM_158_HYDRA_70_M156] 	= {wsType_Weapon, wsType_NURS, wsType_Container} 
wstype_containers[XM_158_HYDRA_70_M274] 	= {wsType_Weapon, wsType_NURS, wsType_Container} 
wstype_containers[XM_158_HYDRA_70_M257] 	= {wsType_Weapon, wsType_NURS, wsType_Container} 

wstype_containers[M134_L]  		= {wsType_Weapon, wsType_GContainer, wsType_Cannon_Cont} -- M134 Minigun Left
wstype_containers[M134_R]  		= {wsType_Weapon, wsType_GContainer, wsType_Cannon_Cont} -- M134 Minigun Right

wstype_containers[M261_HYDRA_70_M151]   = {wsType_Weapon, wsType_NURS, wsType_Container} -- M261 with Mk151 
wstype_containers[M261_HYDRA_70_M156]   = {wsType_Weapon, wsType_NURS, wsType_Container} -- M261 with Mk156

wstype_containers[GUV_YakB_GSHP]  		= {wsType_Weapon, wsType_GContainer, wsType_Cannon_Cont}
wstype_containers[GUV_VOG]  			= {wsType_Weapon, wsType_GContainer, wsType_Cannon_Cont}


