--SKILLS
AVERAGE_SKILL = 4
GOOD_SKILL = 3
HIGH_SKILL = 2
EXCELENT_SKILL = 1
HUMAN_SKILL = 5 --for example , gunners on UH-1
NET_CLIENT_SKILL = 6 --for example , gunners on UH-1

--TARGET SELECTION AND PRIORITIZATION
TARGET_DISANGAGE_TEST_PROBABILITY_LEADER_FACTOR = 0
TARGET_DISANGAGE_TEST_PROBABILITY_WINGMEN_FACTOR = 1
--other wingmen assigned target selection probability = leader_present ? (0.7 * OTHER_WINGMEN_TARGET_SELECTION_PROBABILITY_LEADER_FACTOR + 0.3 * OTHER_WINGMEN_TARGET_SELECTION_PROBABILITY_WINGMEN_FACTOR) :  OTHER_WINGMEN_TARGET_SELECTION_PROBABILITY_WINGMEN_FACTOR
TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR = 2
TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR = 3
--Target prioritization by type propability if most priority target IS NOT AIRDEFENCE  = leader_present ? (0.7 * TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR + 0.3 * TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR) : TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR
AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR = 4
AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR = 5
--Target prioritization by type propability  if most priority target IS AIRDEFENCE = leader_present ? (0.7 * AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR + 0.3 * AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR) : AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR
AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_LEADER_FACTOR = 6
AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_WINGMEN_FACTOR = 7
--SAM prioritization by kill distance probability = leader_present ? (0.7 * AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_LEADER_FACTOR + 0.3 * AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_WINGMEN_FACTOR) : AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_WINGMEN_FACTOR
TARGET_AIRDEFENCE_PROTECTION_TEST_LEADER_FACTOR = 8
TARGET_AIRDEFENCE_PROTECTION_TEST_WINGMEN_FACTOR = 9
--Target airdefence protection test probability = leader_present ? (0.7 * TARGET_AIRDEFENCE_PROTECTION_TEST_LEADER_FACTOR + 0.3 * TARGET_AIRDEFENCE_PROTECTION_TEST_WINGMEN_FACTOR) : TARGET_AIRDEFENCE_PROTECTION_TEST_WINGMEN_FACTOR
--SELF-DEFENCE
MISSILE_EVASION = 10
MISSILE_LAUNCH_REACTION_DELAY_FACTOR = 11
--DETECTION
VISUAL_AND_OPTIC_DETECITON_DIST_FACTOR = 12
VISUAL_AND_OPTIC_DETECITON_TIME_FACTOR = 13
RADAR_DETECTION_TIME_TO_SCAN_PERIOD_COEFF = 14
CAN_USE_RWR = 15
--A2G-ATTACKS
PATHFINDING_IN_MOUNTAIN_TERRAIN_PROBABILITY = 16
NON_VISIBLE_TARGET_ATTACK_WITH_UNGUIDED_WEAPON = 17
MUTLIPLE_ATTACK_ON_APPROACH = 18
ADDITIONAL_BREAKAWAY_DIST_PERCENT = 19
--breakaway dist = breakaway dist * (1.0 +ADDITIONAL_BREAKAWAY_DIST_PERCENT)
--AIMING
WIND_PARAMS_MEASURING_ACCURACY_IN_AIMING = 20 --orderly distribution
TARGET_VELOCITY_MEASURING_ACCURACY_IN_AIMING = 21 --orderly distribution
--BOMBING
BOMBING_ALONG_RUNWAY = 22
BOMB_AIMING_ANGULAR_ERROR = 23  --orderly distribution
STATIC_COLUMN_ATTACK = 24
MOVING_COLUMN_ATTACK = 25 
COLUMN_ATTACK_REQUIRED_BOMB_QTY_CALCULATION_MAX_ERROR = 26
--colum attack req bombs qty = colum attack req bombs optimal qty * (1.0 + random evenly(-1..1) * COLUMN_ATTACK_REQUIRED_BOMB_QTY_CALCULATION_MAX_ERROR)
--CANNON ATTACK
HEAVY_ARMORED_TARGET_ATTACK_FROM_REAR_ASPECT = 27
SHELL_PIERCING_CAPABILITIES_TEST_BEFORE_CANNON_ATTACK = 28
CANNON_FIRE_DISTANCE_COEFF = 29 --effective fire distance = fire distance * fire distance coeff
CANNON_AMMO_OPTIMAL_USING_LEVEL = 30  --0 - best, 2- worst
--ROCKET ATTACK
ROCKET_FIRE_DISTANCE_COEFF = 31
ROCKET_AIMING_ANGULAR_ERROR = 32  ----orderly distribution
ROCKET_AMMO_OPTIMAL_AMMO_USING_LEVEL = 33  --0 - best, 2- worst
--GROUND TARGET MISSILE ATTACK
SHORT_RANGE_ASM_MAX_LAUNCH_DISTANCE_COEFF = 34
--max_launch_distance_by_skill = min_launch_distance + (max_launch_distance - min_launch_distance) * SHORT_RANGE_ASM_MAX_LAUNCH_DISTANCE_COEFF
ATTACK_REQUIRED_MISSILES_QTY_CALCULATION = 35
BREAKAWAY_FOR_MULTIPLE_MISSILE_ATTACK_IN_SINGLE_APPROACH = 36
MISSILE_LAUNCH_MIN_INTERVAL = 37
--A2A WARFARE
MULTILAUNCH_QTY = 38
AA_MISSILE_MAX_LAUNCH_DISTANCE_COEFF = 39
MAX_NY_RATIO = 40
-- AI ERRORS
MISSING_SCALE_COEF 			= 41
VULNERABLE_ZONES_SELECTION 	= 42
AIMING_ERROR_FIXTURE_TIME 	= 43


factors = {
	[AVERAGE_SKILL] = {
		--TARGET SELECTION AND PRIORITIZATION
		[TARGET_DISANGAGE_TEST_PROBABILITY_LEADER_FACTOR] = 1.0,
		[TARGET_DISANGAGE_TEST_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR] = 1.0,
		[TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_LEADER_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[TARGET_AIRDEFENCE_PROTECTION_TEST_LEADER_FACTOR] = 1.0,
		[TARGET_AIRDEFENCE_PROTECTION_TEST_WINGMEN_FACTOR] = 1.0,
		--SELF-DEFENCE
		[MISSILE_EVASION] = false,
		[MISSILE_LAUNCH_REACTION_DELAY_FACTOR] = 10.0,
		--DETECTION
		[VISUAL_AND_OPTIC_DETECITON_DIST_FACTOR] = 0.55,
		[VISUAL_AND_OPTIC_DETECITON_TIME_FACTOR] = 2.0,
		[RADAR_DETECTION_TIME_TO_SCAN_PERIOD_COEFF] = 4,
		[CAN_USE_RWR] = true,
		--A2G-ATTACKS
		[PATHFINDING_IN_MOUNTAIN_TERRAIN_PROBABILITY] = 0.0,
		[NON_VISIBLE_TARGET_ATTACK_WITH_UNGUIDED_WEAPON] = false,
		[MUTLIPLE_ATTACK_ON_APPROACH] = false,
		[ADDITIONAL_BREAKAWAY_DIST_PERCENT] = 0.6,
		--AIMING
		[WIND_PARAMS_MEASURING_ACCURACY_IN_AIMING] = 0.6,
		[TARGET_VELOCITY_MEASURING_ACCURACY_IN_AIMING] = 0.6,
		--BOMBING
		[BOMBING_ALONG_RUNWAY] = true,
		[BOMB_AIMING_ANGULAR_ERROR] = 2.0,
		[STATIC_COLUMN_ATTACK] = false,
		[MOVING_COLUMN_ATTACK] = false,
		[COLUMN_ATTACK_REQUIRED_BOMB_QTY_CALCULATION_MAX_ERROR] = 1.0,
		--CANNON ATTACK
		[HEAVY_ARMORED_TARGET_ATTACK_FROM_REAR_ASPECT] = true,
		[SHELL_PIERCING_CAPABILITIES_TEST_BEFORE_CANNON_ATTACK] = false,
		[CANNON_FIRE_DISTANCE_COEFF] = 0.7,
		[CANNON_AMMO_OPTIMAL_USING_LEVEL] = 2,
		--ROCKET ATTACK
		[ROCKET_FIRE_DISTANCE_COEFF] = 0.7,
		[ROCKET_AIMING_ANGULAR_ERROR] = 2.0,
		[ROCKET_AMMO_OPTIMAL_AMMO_USING_LEVEL] = 2,		
		--GROUND TARGET MISSILE ATTACK
		[SHORT_RANGE_ASM_MAX_LAUNCH_DISTANCE_COEFF] = 0.7,
		[ATTACK_REQUIRED_MISSILES_QTY_CALCULATION] = false,
		[BREAKAWAY_FOR_MULTIPLE_MISSILE_ATTACK_IN_SINGLE_APPROACH] = false,
		[MISSILE_LAUNCH_MIN_INTERVAL] = 10.0,
		--A2A WARFARE
		[MULTILAUNCH_QTY] = 1,
		[AA_MISSILE_MAX_LAUNCH_DISTANCE_COEFF] = 0.7,
		[MAX_NY_RATIO] = 1.0,
		-- AI ERRORS
		[MISSING_SCALE_COEF] 			= 0.7,
		[VULNERABLE_ZONES_SELECTION]	= 0.0,
		[AIMING_ERROR_FIXTURE_TIME] 	= 10.0
	},
	[GOOD_SKILL] = {
		--TARGET SELECTION AND PRIORITIZATION
		[TARGET_DISANGAGE_TEST_PROBABILITY_LEADER_FACTOR] = 1.0,
		[TARGET_DISANGAGE_TEST_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR] = 1.0,
		[TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_LEADER_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[TARGET_AIRDEFENCE_PROTECTION_TEST_LEADER_FACTOR] = 1.0,
		[TARGET_AIRDEFENCE_PROTECTION_TEST_WINGMEN_FACTOR] = 1.0,
		--SELF-DEFENCE
		[MISSILE_EVASION] = true,
		[MISSILE_LAUNCH_REACTION_DELAY_FACTOR] = 5.0,
		--DETECTION
		[VISUAL_AND_OPTIC_DETECITON_DIST_FACTOR] = 0.7,
		[VISUAL_AND_OPTIC_DETECITON_TIME_FACTOR] = 1.5,
		[RADAR_DETECTION_TIME_TO_SCAN_PERIOD_COEFF] = 3,
		[CAN_USE_RWR] = true,
		--A2G-ATTACKS
		[PATHFINDING_IN_MOUNTAIN_TERRAIN_PROBABILITY] = 0.0,
		[NON_VISIBLE_TARGET_ATTACK_WITH_UNGUIDED_WEAPON] = false,
		[MUTLIPLE_ATTACK_ON_APPROACH] = false,
		[ADDITIONAL_BREAKAWAY_DIST_PERCENT] = 0.4,
		--AIMING
		[WIND_PARAMS_MEASURING_ACCURACY_IN_AIMING] = 0.4,
		[TARGET_VELOCITY_MEASURING_ACCURACY_IN_AIMING] = 0.4,
		--BOMBING
		[BOMBING_ALONG_RUNWAY] = true,
		[BOMB_AIMING_ANGULAR_ERROR] = 1.5,
		[STATIC_COLUMN_ATTACK] = true,
		[MOVING_COLUMN_ATTACK] = false,
		[COLUMN_ATTACK_REQUIRED_BOMB_QTY_CALCULATION_MAX_ERROR] = 0.6,
		--CANNON ATTACK
		[HEAVY_ARMORED_TARGET_ATTACK_FROM_REAR_ASPECT] = false,
		[SHELL_PIERCING_CAPABILITIES_TEST_BEFORE_CANNON_ATTACK] = false,
		[CANNON_FIRE_DISTANCE_COEFF] = 0.8,
		[CANNON_AMMO_OPTIMAL_USING_LEVEL] = 1,
		--ROCKET ATTACK
		[ROCKET_FIRE_DISTANCE_COEFF] = 0.8,
		[ROCKET_AIMING_ANGULAR_ERROR] = 1.5,
		[ROCKET_AMMO_OPTIMAL_AMMO_USING_LEVEL] = 1,		
		--GROUND TARGET MISSILE ATTACK
		[SHORT_RANGE_ASM_MAX_LAUNCH_DISTANCE_COEFF] = 0.8,
		[ATTACK_REQUIRED_MISSILES_QTY_CALCULATION] = false,
		[BREAKAWAY_FOR_MULTIPLE_MISSILE_ATTACK_IN_SINGLE_APPROACH] = false,
		[MISSILE_LAUNCH_MIN_INTERVAL] = 8.0,
		--A2A WARFARE
		[MULTILAUNCH_QTY] = 2,
		[AA_MISSILE_MAX_LAUNCH_DISTANCE_COEFF] = 0.8,
		[MAX_NY_RATIO] = 1.0,
		-- AI ERRORS
		[MISSING_SCALE_COEF] = 0.5,
		[VULNERABLE_ZONES_SELECTION]	= 0.0,
		[AIMING_ERROR_FIXTURE_TIME] 	= 7.0
	},
	[HIGH_SKILL] = {
		--TARGET SELECTION AND PRIORITIZATION
		[TARGET_DISANGAGE_TEST_PROBABILITY_LEADER_FACTOR] = 1.0,
		[TARGET_DISANGAGE_TEST_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR] = 1.0,
		[TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_LEADER_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[TARGET_AIRDEFENCE_PROTECTION_TEST_LEADER_FACTOR] = 1.0,
		[TARGET_AIRDEFENCE_PROTECTION_TEST_WINGMEN_FACTOR] = 1.0,
		--SELF-DEFENCE
		[MISSILE_EVASION] = true,
		[MISSILE_LAUNCH_REACTION_DELAY_FACTOR] = 2.0,
		--DETECTION
		[VISUAL_AND_OPTIC_DETECITON_DIST_FACTOR] = 0.85,
		[VISUAL_AND_OPTIC_DETECITON_TIME_FACTOR] = 1.2,
		[RADAR_DETECTION_TIME_TO_SCAN_PERIOD_COEFF] = 2,
		[CAN_USE_RWR] = true,
		--A2G-ATTACKS
		[PATHFINDING_IN_MOUNTAIN_TERRAIN_PROBABILITY] = 1.0,
		[NON_VISIBLE_TARGET_ATTACK_WITH_UNGUIDED_WEAPON] = true,
		[MUTLIPLE_ATTACK_ON_APPROACH] = true,
		[ADDITIONAL_BREAKAWAY_DIST_PERCENT] = 0.2,
		--AIMING
		[WIND_PARAMS_MEASURING_ACCURACY_IN_AIMING] = 0.2,
		[TARGET_VELOCITY_MEASURING_ACCURACY_IN_AIMING] = 0.2,
		--BOMBING
		[BOMBING_ALONG_RUNWAY] = true,
		[BOMB_AIMING_ANGULAR_ERROR] = 0.7,
		[STATIC_COLUMN_ATTACK] = true,
		[MOVING_COLUMN_ATTACK] = true,
		[COLUMN_ATTACK_REQUIRED_BOMB_QTY_CALCULATION_MAX_ERROR] = 0.3,
		--CANNON ATTACK
		[HEAVY_ARMORED_TARGET_ATTACK_FROM_REAR_ASPECT] = true,
		[SHELL_PIERCING_CAPABILITIES_TEST_BEFORE_CANNON_ATTACK] = true,
		[CANNON_FIRE_DISTANCE_COEFF] = 0.9,
		[CANNON_AMMO_OPTIMAL_USING_LEVEL] = 1,
		--ROCKET ATTACK
		[ROCKET_FIRE_DISTANCE_COEFF] = 0.9,
		[ROCKET_AIMING_ANGULAR_ERROR] = 0.7,
		[ROCKET_AMMO_OPTIMAL_AMMO_USING_LEVEL] = 1,
		--GROUND TARGET MISSILE ATTACK
		[SHORT_RANGE_ASM_MAX_LAUNCH_DISTANCE_COEFF] = 0.9,
		[ATTACK_REQUIRED_MISSILES_QTY_CALCULATION] = true,
		[BREAKAWAY_FOR_MULTIPLE_MISSILE_ATTACK_IN_SINGLE_APPROACH] = true,
		[MISSILE_LAUNCH_MIN_INTERVAL] = 6.0,
		--A2A WARFARE
		[MULTILAUNCH_QTY] = 4,
		[AA_MISSILE_MAX_LAUNCH_DISTANCE_COEFF] = 0.9,
		[MAX_NY_RATIO] = 1.0,
		-- AI ERRORS
		[MISSING_SCALE_COEF] = 0.25,
		[VULNERABLE_ZONES_SELECTION]	= 0.5,
		[AIMING_ERROR_FIXTURE_TIME] 	= 4.0
	},	
	[EXCELENT_SKILL] = {
		--TARGET SELECTION AND PRIORITIZATION
		[TARGET_DISANGAGE_TEST_PROBABILITY_LEADER_FACTOR] = 1.0,
		[TARGET_DISANGAGE_TEST_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR] = 1.0,
		[TARGET_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_LEADER_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_TYPE_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_LEADER_FACTOR] = 1.0,
		[AIRDEFENCE_PRIORITIZATION_BY_KILL_DIST_PROBABILITY_WINGMEN_FACTOR] = 1.0,
		[TARGET_AIRDEFENCE_PROTECTION_TEST_LEADER_FACTOR] = 1.0,
		[TARGET_AIRDEFENCE_PROTECTION_TEST_WINGMEN_FACTOR] = 1.0,
		--SELF-DEFENCE
		[MISSILE_EVASION] = true,
		[MISSILE_LAUNCH_REACTION_DELAY_FACTOR] = 0.0,
		--DETECTION
		[VISUAL_AND_OPTIC_DETECITON_DIST_FACTOR] = 1.0,
		[VISUAL_AND_OPTIC_DETECITON_TIME_FACTOR] = 1.0,		
		[RADAR_DETECTION_TIME_TO_SCAN_PERIOD_COEFF] = 1,
		[CAN_USE_RWR] = true,
		--A2G-ATTACKS
		[PATHFINDING_IN_MOUNTAIN_TERRAIN_PROBABILITY] = 1.0,
		[NON_VISIBLE_TARGET_ATTACK_WITH_UNGUIDED_WEAPON] = true,
		[MUTLIPLE_ATTACK_ON_APPROACH] = true,
		[ADDITIONAL_BREAKAWAY_DIST_PERCENT] = 0.0,
		--AIMING
		[WIND_PARAMS_MEASURING_ACCURACY_IN_AIMING] = 0.0,
		[TARGET_VELOCITY_MEASURING_ACCURACY_IN_AIMING] = 0.0,
		--BOMBING
		[BOMBING_ALONG_RUNWAY] = true,
		[BOMB_AIMING_ANGULAR_ERROR] = 0.0,
		[STATIC_COLUMN_ATTACK] = true,
		[MOVING_COLUMN_ATTACK] = true,
		[COLUMN_ATTACK_REQUIRED_BOMB_QTY_CALCULATION_MAX_ERROR] = 0.0,
		--CANNON ATTACK
		[HEAVY_ARMORED_TARGET_ATTACK_FROM_REAR_ASPECT] = true,
		[SHELL_PIERCING_CAPABILITIES_TEST_BEFORE_CANNON_ATTACK] = true,
		[CANNON_FIRE_DISTANCE_COEFF] = 1.0,
		[CANNON_AMMO_OPTIMAL_USING_LEVEL] = 0,
		--ROCKET ATTACK
		[ROCKET_FIRE_DISTANCE_COEFF] = 1.0,
		[ROCKET_AIMING_ANGULAR_ERROR] = 0.0,
		[ROCKET_AMMO_OPTIMAL_AMMO_USING_LEVEL] = 0,
		--GROUND TARGET MISSILE ATTACK
		[SHORT_RANGE_ASM_MAX_LAUNCH_DISTANCE_COEFF] = 1.0,
		[ATTACK_REQUIRED_MISSILES_QTY_CALCULATION] = true,
		[BREAKAWAY_FOR_MULTIPLE_MISSILE_ATTACK_IN_SINGLE_APPROACH] = true,
		[MISSILE_LAUNCH_MIN_INTERVAL] = 4.0,
		--A2A WARFARE
		[MULTILAUNCH_QTY] = 0,
		[AA_MISSILE_MAX_LAUNCH_DISTANCE_COEFF] = 1.0,
		[MAX_NY_RATIO] = 1.0,
		-- AI ERRORS
		[MISSING_SCALE_COEF] = 0.05,
		[VULNERABLE_ZONES_SELECTION]	= 1.0,
		[AIMING_ERROR_FIXTURE_TIME] 	= 2.0
	},
	[HUMAN_SKILL] = {
		--DETECTION
		[VISUAL_AND_OPTIC_DETECITON_DIST_FACTOR] = 27.0,
		[VISUAL_AND_OPTIC_DETECITON_TIME_FACTOR] = 1.0,		
	},
	[NET_CLIENT_SKILL] = {
		--DETECTION
		[VISUAL_AND_OPTIC_DETECITON_DIST_FACTOR] = 27.0,
		[VISUAL_AND_OPTIC_DETECITON_TIME_FACTOR] = 1.0,		
	}
}