--generated by Make/build_speech_index.py at Wed Sep  9 01:45:05 2020 UTC (and manually edited)
CHN = {
  ["Common"] = {
    ["atc"] = {
      ["1"] = {
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
      },
    },
    ["awacs"] = {
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
    },
    ["betty"] = {
      ["messages"] = {},
    },
    ["ground crew"] = {
      ["messages"] = {},
    },
    ["landing"] = {},
    ["player"] = {
      ["alphabet"] = {},
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
      ["target"] = {},
      ["weapon"] = {},
    },
    ["tanker"] = {
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
    },
    ["wingman"] = {
      ["1"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
    },
  },
}
ENG = {
  ["A-10A"] = {
    ["a-10 vmu"] = {
      ["messages"] = {},
    },
  },
  ["A-10C"] = {
    ["a-10 vmu"] = {
      ["messages"] = {},
    },
  },
  ["A-10C_2"] = {
    ["a-10 vmu"] = {
      ["messages"] = {},
    },
  },
  ["Common"] = {
    ["allied flight"] = {
      ["china"] = {
        ["airdefence"] = {},
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["france"] = {
        ["airdefence"] = {},
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["germany"] = {
        ["airdefence"] = {},
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["greece"] = {
        ["airdefence"] = {},
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["russia"] = {
        ["airdefence"] = {},
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["spain"] = {
        ["airdefence"] = {},
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["uk"] = {
        ["airdefence"] = {},
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["usa"] = {
        ["1"] = {
          ["airdefence"] = {},
          ["callsign"] = {},
          ["digits"] = {},
          ["messages"] = {},
          ["numbers"] = {},
          ["target"] = {},
        },
        ["2"] = {
          ["airdefence"] = {},
          ["callsign"] = {},
          ["digits"] = {},
          ["messages"] = {},
          ["numbers"] = {},
          ["target"] = {},
        },
        ["3"] = {
          ["airdefence"] = {},
          ["callsign"] = {},
          ["digits"] = {},
          ["messages"] = {},
          ["numbers"] = {},
          ["target"] = {},
        },
      },
    },
    ["atc"] = {
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
    },
    ["atc_navy_approach_tower"] = {
      ["digits"] = {},
      ["messages"] = {},
    },
    ["atc_navy_departure"] = {
      ["digits"] = {},
      ["messages"] = {},
    },
    ["atc_navy_lso"] = {
      ["messages"] = {},
    },
    ["atc_navy_marshal"] = {
      ["digits"] = {},
      ["messages"] = {},
    },
    ["awacs"] = {
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
    },
    ["betty"] = {
      ["messages"] = {},
    },
    ["external cargo"] = {
      ["messages"] = {},
    },
    ["ground crew"] = {
      ["messages"] = {},
    },
    ["jtac"] = {
      ["airdefence"] = {},
      ["alphabet"] = {},
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
      ["target"] = {},
      ["weapon"] = {},
    },
    ["landing"] = {},
    ["navy_player"] = {
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
    },
    ["player"] = {
      ["alphabet"] = {},
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
      ["target"] = {},
      ["weapon"] = {},
    },
    ["tanker"] = {
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
    },
    ["wingman"] = {
      ["1"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["3"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
    },
  },
  ["Ka-50"] = {
    ["almaz"] = {
      ["messages"] = {},
    },
    ["player"] = {
      ["alphabet"] = {},
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
      ["target"] = {},
      ["weapon"] = {},
    },
    ["wingman"] = {
      ["1"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["3"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
    },
  },
  ["Mi-8MT"] = {
    ["messages"] = {},
    ["ri65"] = {
      ["messages"] = {},
    },
  },
}
GER = {
  ["Common"] = {
    ["betty"] = {
      ["messages"] = {},
    },
  },
}
GRC = {
  ["Common"] = {
    ["ground crew"] = {
      ["messages"] = {},
    },
    ["player"] = {
      ["alphabet"] = {},
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
      ["target"] = {},
      ["weapon"] = {},
    },
    ["wingman"] = {
      ["1"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["3"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
    },
  },
  ["Ka-50"] = {
    ["player"] = {
      ["alphabet"] = {},
      ["callsign"] = {},
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
      ["target"] = {},
      ["weapon"] = {},
    },
    ["wingman"] = {
      ["1"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["3"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
    },
  },
}
RUS = {
  ["Common"] = {
    ["allied flight"] = {
      ["1"] = {
        ["airdefence"] = {},
        ["digits"] = {},
        ["indexes"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["2"] = {
        ["airdefence"] = {},
        ["digits"] = {},
        ["indexes"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["3"] = {
        ["airdefence"] = {},
        ["digits"] = {},
        ["indexes"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["4"] = {
        ["airdefence"] = {},
        ["digits"] = {},
        ["indexes"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["5"] = {
        ["airdefence"] = {},
        ["digits"] = {},
        ["indexes"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
      ["6"] = {
        ["airdefence"] = {},
        ["digits"] = {},
        ["indexes"] = {},
        ["messages"] = {},
        ["numbers"] = {},
        ["target"] = {},
      },
    },
    ["atc"] = {
      ["1"] = {
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
      },
      ["3"] = {
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
      },
      ["4"] = {
        ["callsign"] = {},
        ["digits"] = {},
        ["messages"] = {},
      },
    },
    ["awacs"] = {
      ["callsign"] = {},
      ["digits"] = {},
      ["indexes"] = {},
      ["messages"] = {},
      ["numbers"] = {},
    },
    ["betty"] = {
      ["messages"] = {},
    },
    ["external cargo"] = {
      ["messages"] = {},
    },
    ["ground crew"] = {
      ["messages"] = {},
    },
    ["landing"] = {},
    ["player"] = {
      ["alphabet"] = {},
      ["callsign"] = {},
      ["digits"] = {},
      ["indexes"] = {},
      ["messages"] = {},
      ["numbers"] = {},
      ["target"] = {},
      ["weapon"] = {},
    },
    ["tanker"] = {
      ["digits"] = {},
      ["messages"] = {},
      ["numbers"] = {},
    },
    ["wingman"] = {
      ["1"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["3"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
    },
  },
  ["Ka-50"] = {
    ["almaz"] = {
      ["messages"] = {},
    },
    ["wingman"] = {
      ["1"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["2"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
      ["3"] = {
        ["digits"] = {},
        ["messages"] = {},
      },
    },
  },
  ["Mi-8MT"] = {
    ["messages"] = {
      ["checklist"] = {
        ["01"] = {},
        ["02"] = {},
        ["03"] = {},
        ["04"] = {},
        ["05"] = {},
        ["06"] = {},
        ["wind"] = {},
      },
      ["modules"] = {
        ["01"] = {},
        ["02"] = {},
        ["03"] = {},
        ["04"] = {},
        ["06"] = {},
        ["08"] = {},
        ["digits"] = {},
      },
      ["procedures"] = {},
    },
    ["ri65"] = {
      ["messages"] = {},
    },
  },
}
